-- schema.sql
CREATE DATABASE IF NOT EXISTS digital_id;
USE digital_id;

-- users (both students and lecturers)
CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(50) PRIMARY KEY,        -- user id (student id or lecturer id)
  name VARCHAR(150) NOT NULL,
  password VARCHAR(150) NOT NULL,    -- plain text for simplicity (NOT secure)
  role ENUM('student','lecturer') NOT NULL,
  major VARCHAR(150) DEFAULT NULL,   -- student only
  department VARCHAR(150) DEFAULT NULL,
  photo_url TEXT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- courses
CREATE TABLE IF NOT EXISTS courses (
  course_id VARCHAR(50) PRIMARY KEY,
  course_name VARCHAR(200) NOT NULL,
  lecturer_id VARCHAR(50) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (lecturer_id) REFERENCES users(id) ON DELETE SET NULL
);

-- enrollments (student enrolled courses)
CREATE TABLE IF NOT EXISTS enrollments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  student_id VARCHAR(50) NOT NULL,
  course_id VARCHAR(50) NOT NULL,
  enrolled_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_enroll (student_id, course_id),
  FOREIGN KEY (student_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (course_id) REFERENCES courses(course_id) ON DELETE CASCADE
);

-- attendance_codes (generated by lecturer for a course; valid_until defines expiry)
CREATE TABLE IF NOT EXISTS attendance_codes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  course_id VARCHAR(50) NOT NULL,
  code VARCHAR(100) NOT NULL,
  created_by VARCHAR(50) NOT NULL, -- lecturer id
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  valid_until TIMESTAMP NOT NULL
);

-- attendance records (student submissions)
CREATE TABLE IF NOT EXISTS attendance (
  id INT AUTO_INCREMENT PRIMARY KEY,
  student_id VARCHAR(50) NOT NULL,
  student_name VARCHAR(150) NOT NULL,
  course_id VARCHAR(50) NOT NULL,
  code_used VARCHAR(100) NOT NULL,
  submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_attendance (student_id, course_id, DATE(submitted_at)),
  FOREIGN KEY (student_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (course_id) REFERENCES courses(course_id) ON DELETE CASCADE
);
